---

# Where you ran base16-builder, we need to know this so that we know where to
# look for all the colorschemes.
builder_directory: "~/Applications/base16-builder"

# If to use the light theme instead of the dark one, the reason for this not
# being `use_dark_theme` is because the author prefers dark themes.
use_light_theme: false

# If to use 256 colors, which may not be supported by some terminals.
use_256_colors: true

# A list of which applications you want to install.
colorschemes_to_install:
    -
        # The folder to look into, found in the builder_directory.
        folder_name: "xresources"
        # Where to save the colorscheme file.
        save_to: "~/.Xresources-colorscheme"
        # No extension is specified here, because the files' extension is
        # .xresources.
    -
        folder_name: "shell"
        save_to: "~/Scripts/base16-colorscheme.sh"
        # We need to specify the extension here, because the files' extension
        # is not .shell, but rather .sh.
        extension: "sh"

# A list of commands to run after changing the colorscheme; You can use this to
# for example reload your .Xresources or your WM.
run_after_changing:
    - ["xrdb", "~/.Xresources"]
    - ["chmod", "+x", "~/Scripts/base16-colorscheme.sh"]
